### ISSUE TITLE
Release with vector dependency fix

### ISSUE THREAD

**Issue by jtdaugherty** [acowley/ply-loader#5]
I noticed recently that the fix I contributed is not present in the version that is available on Hackage. Would it be possible for you to push a new version to Hackage including that fix?

**Comment by acowley** [comment]
Shoot, sorry! Done. 

I also pushed a version to master that -- I hope -- updates the `vector` code to work with 0.11, but I haven't had a chance to test it yet. If you have a chance to try it, let me know if it works for you!

**Comment by jtdaugherty** [comment]
Okay, will do. Thank you!
